Repository LOCCouncil/Moonglow, pull requests merged in 2018-10, with the labels that each got.

#82 remove stupid directory
  .vs/ProjectSettings.json
  .vs/ShadowShard/v15/.suo
  .vs/VSWorkspaceState.json
  .vs/slnx.sqlite
Labels: hacktoberfest

#88 Update ping.js
  commands/ping.js
Labels: enhancement, hacktoberfest

#90 Update shard.js
  shard.js
Labels: hacktoberfest

#94 Updates Version to 3.6.5
  commands/stats.js
Labels: enhancement, hacktoberfest

#95 Updates version in info.js
  commands/info.js
Labels: enhancement, hacktoberfest

#98 Fix Grammatical Errors
  modules/functions.js
Labels: bug fix, enhancement

#100 Add/Fix Commands
  commands/getperms.js
  commands/whois.js
Labels: enhancement

#125 Update and rename moonglowpm2.json to deltapm2.json
  deltapm2.json
Labels: enhancement

#124 Add system name to the author field
  commands/sysinfo.js
Labels: enhancement

#146 fix sysinfo for linux and mac
  commands/sysinfo.js
Labels: bug fix
