Repository LOCCouncil/Moonglow, pull requests merged in 2018-09, with the labels that each got.

#8 Kick
  commands/kick.js
  commands/whois.js
Labels: bug, enhancement, help wanted

#11 Add files via upload
  shiba.js
Labels: enhancement, question

#13 Update checkinvites.js
  commands/checkinvites.js
Labels: enhancement

#18 Make the code look nicer
  commands/addrole.js
  commands/ban.js
  commands/game.js
  commands/invite.js
  commands/shiba.js
  commands/stats.js
  commands/whois.js
  events/error.js
Labels: enhancement

#31 Update shiba.js
  commands/shiba.js
Labels: enhancement

#36 Update addrole.js
  commands/addrole.js
Labels: bug fix, enhancement

#35 Update issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: enhancement

#32 Update LICENSE
  LICENSE
Labels: enhancement

#33 File is no longer needed.
  .travis.yml
Labels: bug fix, help wanted

#29 Simplify the Math error commands
  commands/math.js
Labels: enhancement

#38 Disable Commands that have severe Functionality Bugs
  commands/addrole.js
  commands/ban.js
  commands/kick.js
Labels: bug, help wanted

#41 Bug Fix for Kick
  commands/kick.js
Labels: bug fix

#42 Create purge.js
  commands/purge.js
Labels: bug fix, enhancement

#43 Add Uptime & Edit Ping
  commands/ping.js
  commands/uptime.js
Labels: enhancement

#50 Fix the game "TypeError" bug
  commands/game.js
Labels: bug fix

#52 Dev Push
  commands/game.js
  commands/whois.js
  config.js.example
  node_modules/mathjs/package.json
Labels: bug fix, enhancement

#54 Update Type/Branch Details
  commands/game.js
  commands/info.js
  commands/invite.js
  commands/ping.js
  commands/stats.js
  commands/uptime.js
  commands/whois.js
  events/ready.js
Labels: enhancement

#61 Move Licensing and MD files
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/LICENSE
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#68 Allow game to be used with an ID
  commands/game.js
Labels: enhancement
